NCLabs\Bundle\GalleryBundle\Entity\ReleaseSchedule:
  type: entity
  table: release_schedule
  fields:
    releaseId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: release_id
      generator:
        strategy: IDENTITY
    galleryId:
      type: integer
      unsigned: false
      nullable: false
      column: gallery_id
    releaseTime:
      type: datetime
      unsigned: false
      nullable: false
      column: release_time
  repositoryClass: NCLabs\Bundle\GalleryBundle\Entity\ReleaseScheduleRepository
  lifecycleCallbacks: {  }
